---
- name: Dell Test
  hosts: dell_switches
  gather_facts: false

  tasks:
    - name: Show Version
      dellemc.os6.os6_command:
        commands:
          - show version
      register: result

    - name: Ausgabe
      ansible.builtin.debug:
        msg: "{{ result.stdout[0] }}"
