---
- name: Dell Interface-Status anzeigen
  hosts: dell_switches
  gather_facts: false

  tasks:
    - name: Interface-Status auslesen
      dellemc.os6.os6_command:
        commands:
          - show interfaces status
      register: result

    - name: Interface-Status ausgeben
      ansible.builtin.debug:
        msg:
          - "Switch: {{ inventory_hostname }}"
          - "IP-Adresse: {{ ansible_host | default(inventory_hostname) }}"
          - "{{ result.stdout[0] }}"
