---
- name: Show Version
  hosts: cisco_switches
  gather_facts: false

  tasks:
    - name: Show Version
      cisco.ios.ios_command:
        commands:
          - show version
      register: result

    - name: Ausgabe
      ansible.builtin.debug:
        msg: "{{ result.stdout[0] }}"
