---
- name: Dell VLAN Übersicht
  hosts: dell_switches
  gather_facts: false

  vars:
    ansible_become: true
    ansible_become_method: enable
    ansible_command_timeout: 120

  tasks:
    - name: VLAN Informationen auslesen
      dellemc.os6.os6_command:
        commands:
          - show vlan
      register: result

    - name: Header anzeigen
      ansible.builtin.debug:
        msg:
          - "===================================="
          - "Switch: {{ inventory_hostname }}"
          - "IP: {{ ansible_host }}"
          - "===================================="

    - name: VLAN Übersicht anzeigen
      ansible.builtin.debug:
        msg: >-
          VLAN {{ '%-5s' | format(item.split()[0]) }}
          {{ item.split()[1] }}
      loop: >-
        {{
          result.stdout_lines[0]
          | select('match', '^[0-9]')
          | list
        }}
      loop_control:
        label: "{{ item.split()[0] }}"
