---
- name: Dell Image Versionen
  hosts: dell_switches
  gather_facts: false

  tasks:
    - name: Show Version
      dellemc.os6.os6_command:
        commands:
          - show version
      register: result

    - name: Versionszeile auslesen
      ansible.builtin.set_fact:
        image_versions: >-
          {{
            (
              result.stdout[0]
              | regex_search('(?m)^1\s+\S+\s+\S+')
            ).split()
          }}

    - name: Active und Backup Image anzeigen
      ansible.builtin.debug:
        msg:
          - "Switch: {{ inventory_hostname }}"
          - "Active Image: {{ image_versions[1] }}"
          - "Backup Image: {{ image_versions[2] }}"
