---
- name: Show VLANs
  hosts: cisco_switches
  gather_facts: false

  tasks:
    - name: Show VLAN Information
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: result

    - name: Ausgabe
      debug:
        var: result.stdout_lines
