---
- name: Dell Running Config anzeigen
  hosts: dell_switches
  gather_facts: false

  vars:
    ansible_become: true
    ansible_become_method: enable

  tasks:
    - name: Running Config auslesen
      dellemc.os6.os6_command:
        commands:
          - show running-config
      register: result

    - name: Running Config ausgeben
      ansible.builtin.debug:
        msg:
          - "Switch: {{ inventory_hostname }}"
          - "IP-Adresse: {{ ansible_host | default(inventory_hostname) }}"
          - "{{ result.stdout[0] }}"
`
