---
- name: Dell VLANs anzeigen
  hosts: dell_switches
  gather_facts: false

  tasks:
    - name: VLAN-Konfiguration auslesen
      dellemc.os6.os6_command:
        commands:
          - show vlan
      register: result

    - name: VLAN-Konfiguration ausgeben
      ansible.builtin.debug:
        msg:
          - "Switch: {{ inventory_hostname }}"
          - "IP-Adresse: {{ ansible_host | default(inventory_hostname) }}"
          - "{{ result.stdout[0] }}"
